pipeline {
 agent {
 label 'docker-agent'
 }
 stages {
 stage('Run tests and generate reports') {
 steps {
 git url:
'https://github.com/dlambrig/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'master'
 sh '''
 cd Chapter08/sample1
 export KUBECONFIG=/root/.kube/config.modified
 kubectl --insecure-skip-tls-verify apply -f calculator.yaml
 kubectl --insecure-skip-tls-verify apply -f hazelcast.yaml
 '''
 }
 }
 }
}
