pipeline {
    agent { label 'docker-agent' }

    environment {
        REGISTRY = "registry:5000"
    }

    stages {
        stage('Check Branch') {
            steps {
                script {
                    def branchName = env.BRANCH_NAME

                    if (branchName == 'main') {
                        echo "Running main branch pipeline..."
                        env.RUN_MAIN = 'true'
                        env.IMAGE_NAME = 'calculator'
                        env.IMAGE_TAG= '1.0'
                    } else if (branchName == 'feature') {
                        echo "Running Feature branch pipeline..."
                        env.RUN_FEATURE = 'true'
                        env.IMAGE_NAME = 'calculator-feature'
                        env.IMAGE_TAG= '0.1'
                    } 

                    if (branch == 'playground') {
                        echo "Running playground branch pipeline..."
                        env.RUN_PLAYGROUND = 'true'
                    }
                }
            }
        }

        stage('Code coverage') {
            when {
                expression { env.RUN_MAIN == 'true' } 
            }
            steps {
                sh """
                cd Chapter08/sample1
                chmod +x gradlew
                ./gradlew jacocoTestReport
                ./gradlew jacocoTestCoverageVerification
                """
            }
        }

        stage('Compile') {
            when {
                expression { env.RUN_FEATURE == 'true' || env.RUN_PLAYGROUND == 'true'}
            }
            steps {
                    sh """
                    cd Chapter08/sample1
                    chmod +x gradlew
                    ./gradlew compileJava
                    """
               }
        }

        stage('Unit test') {
            when {
                expression { env.RUN_FEATURE == 'true' || env.RUN_PLAYGROUND == 'true' }
            }
            steps {
                    sh """
                    cd Chapter08/sample1
                    chmod +x gradlew
                    ./gradlew test
                    """
               }
        }
        
        stage('Static code analysis') {
            when {
                expression { env.RUN_FEATURE == 'true' || env.RUN_PLAYGROUND == 'true' }
            }
            steps {
                    sh """
                    cd Chapter08/sample1
                    chmod +x gradlew
                    ./gradlew checkstyleMain
                    """
               }
        }

        stage('Package') {
            when {
                expression { env.RUN_FEATURE == 'true' || env.RUN_PLAYGROUND == 'true' }
            }
            steps {
                    sh """
                    cd Chapter08/sample1
                    chmod +x gradlew
                    ./gradlew build
                    """
               }
        }

        stage('Build Image') {
            steps {
                sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} ."
            }
        }
        stage('Push Image') {
            steps {
                sh "docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }
    }
    post {
        success {
            script {
            if (env.RUN_PLAYGROUND == 'false') {
                sh "docker run -d --name my-running-app-${IMAGE_TAG} ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
            }
            echo 'The pipeline ran successfully!'
            }
        }
        failure {
            echo 'The pipeline failed.'
        }
        always {
            publishHTML([
                target: [
                    reportDir: 'Chapter08/sample1/build/reports/checkstyle',
                    reportFiles: 'index.html',
                    reportName: "jacoco checkstyle"
                ]
            ])
        }
    }
}